---
- name: Configure AutoFS master file
  ansible.builtin.template:
    src: etc/auto.master.j2
    dest: /etc/auto.master
    owner: root
    group: root
    mode: '0644'
  notify: reload autofs

- name: Configure AutoFS netboot file
  ansible.builtin.template:
    src: etc/auto.netboot.j2
    dest: /etc/auto.netboot
    owner: root
    group: root
    mode: '0644'
  notify: reload autofs

- name: Start and enable AutoFS service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: autofs
...
