---
- name: Configure IPv4 DHCP server
  ansible.builtin.template:
    src: etc/dhcp/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart dhcpd

- name: Start and enable IPv4 DHCP service
  ansible.builtin.systemd_service:
    state: "{{ 'started' if netboot_dhcp_subnets is defined else 'stopped' }}"
    enabled: "{{ true if netboot_dhcp_subnets is defined else false }}"
    name: dhcpd

- name: Configure IPv6 DHCP server
  ansible.builtin.template:
    src: etc/dhcp/dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart dhcpd6

- name: Start and enable IPv6 DHCP service
  ansible.builtin.systemd_service:
    state: "{{ 'started' if netboot_dhcp6_subnets is defined else 'stopped' }}"
    enabled: "{{ true if netboot_dhcp6_subnets is defined else false }}"
    name: dhcpd6
...
