---
# HTTP
- name: HTTP - Create ipxe directories
  ansible.builtin.file:
    path: '{{ netboot_webroot }}/ipxe/scripts'
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

- name: HTTP - Populate ipxe directory
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ netboot_webroot }}/ipxe'
    remote_src: true
    owner: nginx
    group: nginx
    mode: '0644'
  loop: '{{ netboot_ipxe_files }}'

- name: HTTP - Create ipxe configuration file
  ansible.builtin.template:
    src: ipxe/scripts/boot.ipxe.j2
    dest: '{{ netboot_webroot }}/ipxe/scripts/boot.ipxe'
    owner: nginx
    group: nginx
    mode: '0644'

# TFTP
- name: TFTP - Create ipxe directories
  ansible.builtin.file:
    path: '{{ netboot_tftp_root }}/ipxe/scripts'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: TFTP - Populate ipxe directory
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ netboot_tftp_root }}/ipxe'
    remote_src: true
    owner: root
    group: root
    mode: '0644'
  loop: '{{ netboot_ipxe_files }}'

- name: TFTP - Create ipxe configuration file
  ansible.builtin.template:
    src: ipxe/scripts/boot.ipxe.j2
    dest: '{{ netboot_tftp_root }}/ipxe/scripts/boot.ipxe'
    owner: root
    group: root
    mode: '0644'
...
