---
- name: Set SELinux context for TFTP root directory
  community.general.sefcontext:
    target: '{{ netboot_tftp_root }}(/.*)?'
    setype: tftpdir_rw_t
    state: present
  register: __registered_selinux_tftp

- name: Create TFTP root directory
  ansible.builtin.file:
    path: '{{ netboot_tftp_root }}'
    state: directory
    owner: root
    group: root
    setype: _default
    mode: '0755'

- name: Configure TFTP service
  ansible.builtin.template:
    src: etc/systemd/system/tftp.service.d.j2
    dest: /etc/systemd/system/tftp.service.d
    owner: root
    group: root
    mode: '0644'
  notify: restart tftp

- name: Start and enable TFTP socket
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: tftp.socket
...
